session_name: config
start_directory: ~/
attach: false

windows:
  - window_name: nixos-configuration
    start_directory: ~/nixos-configuration
    panes:
      - shell_command:
        - cmd: hx
  - window_name: shell
