return {
  {
    "aserowy/tmux.nvim",
    keys = {
      {
        "<C-h>",
        function()
          require('tmux').move_left()
        end,
      },
      {
        "<C-l>",
        function()
          require('tmux').move_right()
        end,
      },
      {
        "<C-k>",
        function()
          require('tmux').move_up()
        end,
      },
      {
        "<C-j>",
        function()
          require('tmux').move_down()
        end,
      },
      {
        "<M-h>",
        function()
          require('tmux').resize_left()
        end,
      },
      {
        "<M-l>",
        function()
          require('tmux').resize_right()
        end,
      },
      {
        "<M-k>",
        function()
          require('tmux').resize_up()
        end,
      },
      {
        "<M-j>",
        function()
          require('tmux').resize_down()
        end,
      },
    },
    opts = {
      enable_default_keybindings = false,
    },
  },
}
