[pyprland]
plugins = [
  "scratchpads",
  "expose",
]

[scratchpads.right]
animation = "fromRight"
command = "MellowPlayer"
class = "ColinDuquesnoy.gitlab.com."
lazy = true
size = "40% 90%"

[scratchpads.left]
animation = "fromLeft"
command = "1password"
class = "1password"
lazy = false
size = "40% 90%"

[scratchpads.bottom]
animation = "fromBottom"
command = "valent"
class = "valent"
lazy = false
size = "40% 90%"
