name: config
root: ~/
attach: false

windows:
  - nixos-configuration:
      root: ~/nixos-configuration
      panes:
        - nvim
  - dotfiles:
      root: ~/dotfiles
      panes:
        - nvim
  - shell:
      root: ~/
