name: config
root: ~/

windows:
  - nixos-configuration:
      root: ~/nixos-configuration
      panes:
        - nvim
  - dotfiles:
      root: ~/dotfiles
      panes:
        - nvim
  - shell:
      root: ~/
